import {NextResponse} from 'next/server';
import {getAllGames,getTeamByCode} from '@/lib/db';
import {teamVenues} from '@/lib/teamVenues';
import {getNflInjuries} from '@/lib/apiSports';

type Cached={expiresAt:number;value:any};const cache=globalThis as typeof globalThis&{hqResearchCache?:Map<string,Cached>};cache.hqResearchCache??=new Map();
const record=(games:any[],code:string)=>games.reduce((acc,game)=>{if(game.status!=='final')return acc;const home=game.home_team_id===code;const score=home?game.home_score:game.away_score;const other=home?game.away_score:game.home_score;if(typeof score!=='number'||typeof other!=='number')return acc;if(score>other)acc.wins++;else if(score<other)acc.losses++;else acc.ties++;return acc;},{wins:0,losses:0,ties:0});
async function weather(code:string,game:any){const venue=teamVenues[code];if(!venue||venue.dome||!game)return venue?.dome?{kind:'dome'}:null;const kickoff=Date.parse(`${game.game_date||''} ${game.game_time||'00:00'}`);if(!Number.isFinite(kickoff)||kickoff-Date.now()>10*86400000||kickoff<Date.now()-4*3600000)return null;const points=await fetch(`https://api.weather.gov/points/${venue.lat},${venue.lon}`,{headers:{'User-Agent':'PickemHQ support@pickemhq.co'}});if(!points.ok)return null;const pointData=await points.json();const forecastUrl=pointData.properties?.forecastHourly;if(!forecastUrl)return null;const forecast=await fetch(forecastUrl,{headers:{'User-Agent':'PickemHQ support@pickemhq.co'}});if(!forecast.ok)return null;const periods=(await forecast.json()).properties?.periods||[];const period=periods.find((item:any)=>Math.abs(Date.parse(item.startTime)-kickoff)<4*3600000)||periods[0];return period?{kind:'outdoor',temperature:period.temperature,unit:period.temperatureUnit,wind:period.windSpeed,forecast:period.shortForecast}:null}
export async function GET(_:Request,{params}:{params:{code:string}}){const code=params.code.toUpperCase();const existing=cache.hqResearchCache!.get(code);if(existing&&existing.expiresAt>Date.now())return NextResponse.json({...existing.value,cached:true});const team=getTeamByCode(code);if(!team)return NextResponse.json({error:'Team not found'},{status:404});try{const games=getAllGames().filter(game=>game.home_team_id===team.id||game.away_team_id===team.id);const finals=games.filter(game=>game.status==='final').sort((a,b)=>b.week-a.week);const nextHome=games.filter(game=>game.home_team_id===team.id&&game.status==='scheduled').sort((a,b)=>a.week-b.week)[0];const form=finals.slice(0,5).map(game=>{const home=game.home_team_id===team.id;const score=Number(home?game.home_score:game.away_score);const other=Number(home?game.away_score:game.home_score);return score>other?'W':score<other?'L':'T'});const injuryMap=await getNflInjuries();const injuries=injuryMap.get(team.name.toLowerCase())||[];const value={record:record(finals,team.id),form,weather:await weather(team.id,nextHome),injuries:{available:Boolean(process.env.API_NFL_KEY),players:injuries.slice(0,3),total:injuries.length}};cache.hqResearchCache!.set(code,{value,expiresAt:Date.now()+6*3600000});return NextResponse.json(value,{headers:{'Cache-Control':'public, s-maxage=1800, stale-while-revalidate=21600'}})}catch{return NextResponse.json({record:null,form:[],weather:null,injuries:{available:false,notice:'Research is temporarily unavailable.'}})}}
