'use client';
import {useEffect,useRef,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {useAccount} from '@/components/AccountProvider';
import {hq} from '@/lib/hq/client';
import {field,panel,primary} from '@/components/LeagueConfigFields';
import CommissionerPanel from '@/components/CommissionerPanel';
import EntryPicker from '@/components/EntryPicker';
export default function LeaguePage(){
 const params=useParams();const id=String(params.id);const {session,loading,refresh}=useAccount();
 const [league,setLeague]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [tab,setTab]=useState('picks');const [entryId,setEntryId]=useState('');const [draft,setDraft]=useState<Record<string,any>>({});const [dirty,setDirty]=useState(false);const [entryName,setEntryName]=useState('');const pending=useRef(false);const generation=useRef(0);
 const mine=league?.entries.filter((e:any)=>e.userId===league.me)||[];const entry=mine.find((e:any)=>e.id===entryId);
 function accept(data:any){setLeague(data.league);setDirty(false);}
 async function act(action:string,input:any={}) {
  if(pending.current)return;if(dirty&&!['savePicks','archive','view'].includes(action)&&!window.confirm('Discard your unsaved pick changes?'))return;pending.current=true;setBusy(true);setError('');setMessage('');const seq=++generation.current;
  try{const result=await hq({leagueId:id,week:league?.selectedWeek,action,...input});if(seq!==generation.current)return;
   if(result.league)accept(result);
   if(action==='entry')setEntryName('');
   if(action==='savePicks')setMessage('Picks saved to your account.');
   else if(!['view','archive'].includes(action))setMessage('League updated.');
   if(action==='archive'){const blob=new Blob([JSON.stringify(result.archive,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${league.name}-archive-${input.index+1}.json`;a.click();URL.revokeObjectURL(url);}
   if(['entry','settings','reset','rollover','transfer'].includes(action))void refresh();
  }catch(e){setError(e instanceof Error?e.message:'Unable to load this league.');}finally{if(seq===generation.current){pending.current=false;setBusy(false);}}
 }
 useEffect(()=>{let active=true;generation.current++;pending.current=false;if(session){setBusy(true);hq({action:'view',leagueId:id}).then(data=>{if(active)accept(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});}return()=>{active=false;generation.current++;};},[id,session?.user.id]);
 useEffect(()=>{if(league){const own=league.entries.filter((e:any)=>e.userId===league.me);if(!own.some((e:any)=>e.id===entryId))setEntryId(own[0]?.id||'');}},[league,entryId]);
 useEffect(()=>{if(league){setDraft(Object.fromEntries(league.picks.filter((p:any)=>p.entryId===entryId&&p.week===league.selectedWeek).map((p:any)=>[p.gameId,{teamId:p.teamId,confidence:p.confidence}])));setDirty(false);}},[league,entryId]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{if(!league||dirty)return;const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!pending.current)void act('view');},60000);return()=>clearInterval(timer);},[league?.id,league?.selectedWeek,dirty]);
 function canLeave(){return !dirty||window.confirm('Discard your unsaved pick changes?');}
 function pick(game:any,teamId:string){
  if(busy||game.locked||league.feedStale||!entry||(!entry.alive&&league.config.format==='survivor')||league.selectedWeek!==league.activeWeek)return;
  let next={...draft};if(next[game.id]?.teamId===teamId){delete next[game.id];}else{
   if(league.config.format==='survivor'){
    const limit=league.config.doublePickWeeks.includes(league.selectedWeek)?2:1;
    if(limit===1)next={};
    else if(!next[game.id]&&Object.keys(next).length>=limit){setError('Remove a selected team before choosing another.');return;}
   }
   const used=new Set(Object.values(next).map((p:any)=>p.confidence));const available=Array.from({length:league.games.length},(_,i)=>i+1).find(n=>!used.has(n))||1;
   next[game.id]={teamId,confidence:draft[game.id]?.confidence||available};
  }setDraft(next);setDirty(true);setMessage('');setError('');
 }
 if(loading)return <p>Loading your account…</p>;
 if(!session)return <div className={panel}><h1 className="text-2xl font-black">Sign in to open your league</h1><Link className={`${primary} inline-block mt-5`} href={`/login?next=${encodeURIComponent('/leagues/'+id)}`}>Sign in</Link></div>;
 if(!league)return <div className={panel}>{error?<><p role="alert" className="text-rose-300">{error}</p><Link className="block mt-4 underline text-emerald-400" href="/leagues/join">Join with an invite code</Link><button className="mt-4 underline" onClick={()=>act('view')}>Retry</button></>:<p>Loading your league and NFL scores…</p>}</div>;
 const survivor=league.config.format==='survivor';const required=survivor?(league.config.doublePickWeeks.includes(league.selectedWeek)?2:1):league.games.length;
 const current=league.selectedWeek===league.activeWeek;
 const singleLocked=survivor&&required===1&&Object.keys(draft).some(gameId=>league.games.find((g:any)=>g.id===gameId)?.locked);
 return <div className="space-y-6">
 <header className="rounded-3xl border border-emerald-900 bg-gradient-to-br from-emerald-950 to-slate-900 p-6"><Link className="text-sm text-emerald-400" href="/leagues">← My leagues</Link><p className="text-xs uppercase tracking-widest text-emerald-400 mt-5">{league.config.format==='pickem'?'Straight Pick’em':league.config.format} · NFL {league.season}</p><h1 className="text-3xl font-black mt-2">{league.name}</h1><div className="flex flex-wrap gap-4 mt-4 text-sm text-slate-300"><span>{league.members.length} members</span><span>{league.entries.length} entries</span><span>Starts week {league.startWeek}</span><span>Active week {league.activeWeek}</span></div></header>
 {error&&<p role="alert" className="p-4 rounded-xl bg-rose-950 text-rose-200">{error}</p>}{message&&<p role="status" className="p-4 rounded-xl bg-emerald-950 text-emerald-200">{message}</p>}{league.warnings.map((w:string)=><p className="rounded-xl bg-amber-950 text-amber-200 p-3 text-sm" key={w}>{w}</p>)}
 <section className="flex flex-wrap gap-4 items-center"><div className="mr-auto"><p className="text-xs text-slate-500">INVITE CODE</p><span className="font-mono text-xl tracking-widest">{league.code}</span></div><button className="text-emerald-400 underline" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/leagues/join?code=${league.code}`);setMessage('Invite link copied.');}catch{setMessage(`Share invite code ${league.code}.`);}}}>Copy invite link</button><label className="flex gap-2 items-center text-sm">Week<select className="rounded-lg bg-slate-900 border border-slate-700 p-2" value={league.selectedWeek} disabled={busy} onChange={e=>{if(canLeave())void act('view',{week:Number(e.target.value)});}}>{Array.from({length:19-league.startWeek},(_,i)=>i+league.startWeek).map(w=><option key={w} value={w}>{w}{w===league.activeWeek?' · active':''}</option>)}</select></label><button className="text-slate-300 underline disabled:opacity-40" disabled={busy} onClick={()=>{if(canLeave())void act('view');}}>{busy?'Updating…':'Refresh scores'}</button></section>
 <p className="text-xs text-slate-500">ESPN updated {league.updatedAt?new Date(league.updatedAt).toLocaleString():'not yet'}. Scores refresh while this page is open and you have no unsaved changes.</p>
 <div className="flex gap-2 overflow-x-auto pb-1">{[['picks','My picks'],['entries','My entries'],['standings','Standings & picks'],['settings','Rules & settings'],['history','Season history']].map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold ${tab===value?'bg-emerald-400 text-slate-950':'bg-slate-900 text-slate-400'}`}>{label}</button>)}</div>
 {tab==='picks'&&<><EntryPicker entries={mine} current={entryId} onChange={id=>{if(canLeave())setEntryId(id);}}/><div className={`${panel} flex flex-wrap gap-4 items-center`}><label className="flex-1 min-w-48">Your entry<select className={field} value={entryId} disabled={busy} onChange={e=>{if(canLeave())setEntryId(e.target.value);}}>{mine.map((e:any)=><option value={e.id} key={e.id}>{e.name}{survivor&&!e.alive?' · eliminated':''}</option>)}</select></label><div className="pt-4"><p className="font-bold">{Object.keys(draft).length}/{required} selected</p><p className="text-xs text-slate-400 mt-1">{dirty?'Unsaved changes':'Saved selections'}</p></div><button className={`${primary} mt-4`} disabled={busy||!dirty||!current||league.feedStale} onClick={()=>act('savePicks',{entryId,week:league.selectedWeek,picks:Object.entries(draft).map(([gameId,p]:[string,any])=>({gameId,...p}))})}>{busy?'Saving…':'Save picks'}</button></div>
 <p className="text-sm text-slate-400">{!current?'This week is read-only. Select the active week to submit picks.':survivor?`Choose ${required} team${required>1?'s':''}. No team reuse within this entry. Click a selected team to remove it before saving.`:'Choose a winner for each matchup. Selections are saved together when you press Save picks.'}{league.config.format==='confidence'?' Assign each confidence value once. Higher values earn more points for a correct pick.':''}</p>{survivor&&entry&&!entry.alive&&<p className="text-rose-300">This entry was eliminated in week {entry.eliminatedWeek}.</p>}
 {!league.games.length&&<p className={panel}>No verified NFL games are available for this week.</p>}
 <div className="grid lg:grid-cols-2 gap-4">{league.games.map((g:any)=>{const chosen=draft[g.id];const unavailable=busy||g.locked||(singleLocked&&!draft[g.id])||!current||league.feedStale||(survivor&&!entry?.alive);return <article key={g.id} className={panel}><div className="flex justify-between gap-3 text-xs text-slate-400 mb-4"><time>{new Date(g.kickoff).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time><span className={g.status==='live'?'text-emerald-400 font-bold':''}>{g.status==='scheduled'?(g.locked?'Locked':'Upcoming'):g.detail||g.status}</span></div><div className="grid grid-cols-2 gap-3">{[g.away,g.home].map((t:any)=>{const used=survivor&&league.picks.some((p:any)=>p.entryId===entryId&&p.week!==league.selectedWeek&&p.teamId===t.id&&p.result!=='void');const selected=chosen?.teamId===t.id;return <button key={t.id} disabled={unavailable||used} aria-pressed={selected} onClick={()=>pick(g,t.id)} className={`rounded-xl border p-4 text-left disabled:cursor-default ${selected?'border-emerald-400 bg-emerald-950':'border-slate-700 bg-slate-950'} ${used?'opacity-40':''}`}><img src={t.logo} alt="" className="w-12 h-12 object-contain mb-2"/><span className="font-black text-lg">{t.code} {selected?'✓':''}</span><span className="block text-xs text-slate-400 mt-1">{t.name}</span><span className="block text-sm mt-2">{['live','final'].includes(g.status)?(t.id===g.home.id?g.homeScore:g.awayScore):t.record}</span>{used&&<span className="text-xs text-amber-300">Already used</span>}</button>;})}</div>{league.config.format==='confidence'&&chosen&&<label className="block mt-3 text-sm">Confidence points<select className={field} value={chosen.confidence} disabled={unavailable} onChange={e=>{setDraft({...draft,[g.id]:{...chosen,confidence:Number(e.target.value)}});setDirty(true);}}>{Array.from({length:league.games.length},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} points</option>)}</select></label>}</article>;})}</div>
 </>}
 {tab==='entries'&&<section className={`${panel} space-y-5`}><h2 className="font-bold text-xl">Your league entries</h2><div className="space-y-3">{mine.map((e:any)=><div key={e.id} className="flex flex-wrap justify-between gap-3 p-4 bg-slate-950 rounded-xl"><span>{e.name} · {survivor?(e.alive?'Alive':`Eliminated week ${e.eliminatedWeek}`):`${e.points} points`}</span><div className="flex gap-4"><button disabled={busy} className="text-slate-400 underline" onClick={()=>{const name=window.prompt('Entry name',e.name);if(name)void act('renameEntry',{entryId:e.id,name});}}>Rename</button><button className="text-emerald-400 underline" onClick={()=>{if(canLeave()){setEntryId(e.id);setTab('picks');}}}>Make picks</button></div></div>)}</div><form className="space-y-3" onSubmit={e=>{e.preventDefault();void act('entry',{name:entryName});}}><label className="block">New entry name<input required minLength={2} maxLength={40} className={field} value={entryName} onChange={e=>setEntryName(e.target.value)}/></label><p className="text-sm text-slate-400">{mine.length}/{league.config.maxEntries} entries used. Add entries before the league’s first kickoff.</p><button className={primary} disabled={busy||mine.length>=league.config.maxEntries}>Add entry</button></form></section>}
 {tab==='standings'&&<section className={`${panel} overflow-x-auto`}><h2 className="text-xl font-bold mb-4">Season standings · Week {league.selectedWeek} picks</h2><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr>{['Rank','Entry / player',survivor?'Status':'Points','W–L–T','This week’s picks'].map(h=><th className="p-3 whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{league.entries.map((e:any,i:number)=>{const signature=(x:any)=>survivor?`${x.alive}:${x.eliminatedWeek||99}:${x.wins}`:`${x.points}:${league.config.tiebreaker==='correct-picks'?x.wins:0}`;const rank=league.entries.findIndex((x:any)=>signature(x)===signature(e))+1;const selected=league.picks.filter((p:any)=>p.entryId===e.id&&p.week===league.selectedWeek);const total=league.submissions.find((s:any)=>s.entryId===e.id)?.count||0;return <tr className="border-t border-slate-800" key={e.id}><td className="p-3">{rank}</td><td className="p-3"><details><summary className="cursor-pointer font-bold">{e.avatar} {e.name}</summary><p className="text-slate-400 mt-2">{e.playerName}</p><p className="text-slate-500 mt-1">{league.entries.filter((x:any)=>x.userId===e.userId).length} entries in this league</p></details></td><td className="p-3 whitespace-nowrap">{survivor?(e.alive?'Alive':`Out · W${e.eliminatedWeek}`):e.points}</td><td className="p-3 whitespace-nowrap">{e.wins}–{e.losses}–{e.ties}</td><td className="p-3">{selected.map((p:any)=><span key={p.gameId} className={`inline-block mr-2 ${p.result==='win'?'text-emerald-400':p.result==='loss'?'text-rose-400':'text-slate-300'}`}>{p.team?.code||p.teamId}{league.config.format==='confidence'?` (${p.confidence})`:''} · {p.result}</span>)}{total>selected.length&&<span className="text-slate-500">{total-selected.length} hidden until lock</span>}{total===0&&'No picks'}</td></tr>;})}</tbody></table></section>}
 {tab==='settings'&&<CommissionerPanel key={league.id+':'+league.ownerId} league={league} act={act} busy={busy}/>}
 {tab==='history'&&<div className="space-y-5"><section className={`${panel} overflow-x-auto`}><h2 className="font-bold text-xl mb-4">Your season pick history</h2><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Entry</th><th className="p-3">Week</th><th className="p-3">Team</th><th className="p-3">Result</th></tr></thead><tbody>{league.picks.filter((p:any)=>mine.some((e:any)=>e.id===p.entryId)).sort((a:any,b:any)=>a.week-b.week).map((p:any)=><tr key={p.entryId+p.week+p.gameId} className="border-t border-slate-800"><td className="p-3">{mine.find((e:any)=>e.id===p.entryId)?.name}</td><td className="p-3">{p.week}</td><td className="p-3">{p.team?.name||p.teamId}</td><td className="p-3 capitalize">{p.result}</td></tr>)}</tbody></table></section><section className={panel}><h2 className="font-bold text-xl mb-4">Archived competitions</h2>{!league.archives.length&&<p className="text-slate-400">No resets or season rollovers yet. Weekly history stays above.</p>}{league.archives.map((a:any,i:number)=><div key={i} className="py-3 border-b border-slate-800 flex flex-wrap gap-3 justify-between"><span>{a.season} · {a.reason} · {new Date(a.at).toLocaleDateString()}</span><button className="text-emerald-400 underline" disabled={busy} onClick={()=>act('archive',{index:i})}>Download my archived picks</button></div>)}</section></div>}
 </div>;
}
