'use client';
import {useState} from 'react';
import LeagueConfigFields,{panel,field,primary} from './LeagueConfigFields';
export default function CommissionerPanel({league,act,busy}:{league:any;act:(action:string,input?:any)=>Promise<void>;busy:boolean}) {
 const [form,setForm]=useState({...league.config,name:league.name});const [deadline,setDeadline]=useState('');const [confirmation,setConfirmation]=useState('');const [startWeek,setStartWeek]=useState(league.activeWeek);const [season,setSeason]=useState(league.season+1);const [nextOwner,setNextOwner]=useState('');
 const owner=league.ownerId===league.me;
 return <div className="space-y-5"><section className={panel}><h2 className="text-xl font-bold mb-4">League rules</h2><dl className="grid sm:grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Format</dt><dd className="capitalize">{league.config.format}</dd></div><div><dt className="text-slate-500">Entry limit</dt><dd>{league.config.maxEntries} per person</dd></div><div><dt className="text-slate-500">Deadlines</dt><dd>{league.config.deadlineMode==='first-game'?'All picks lock at the first kickoff':'Each selected game locks at kickoff'}</dd></div><div><dt className="text-slate-500">Buy-in tracking</dt><dd>${league.config.buyIn.toFixed(2)} · no payments collected</dd></div><div><dt className="text-slate-500">Tiebreaker</dt><dd>{league.config.tiebreaker==='shared'?'Shared rank':'Most correct picks'}</dd></div>{league.config.format==='survivor'&&<><div><dt className="text-slate-500">Double-pick weeks</dt><dd>{league.config.doublePickWeeks.join(', ')||'None'}</dd></div><div><dt className="text-slate-500">Tied games</dt><dd>{league.config.tiesLose?'Eliminate the entry':'Entry survives'}</dd></div></>}</dl><p className="text-slate-400 text-sm mt-5">{league.config.format==='survivor'?'Teams cannot be reused within an entry. Missing a required pick eliminates the entry once the week’s games are final. Canceled games are void.':'Missing picks and tied games earn zero points. Canceled games are void.'} Picks become visible to others when their game or league deadline locks. Weeks advance with the NFL calendar; previous picks are retained.</p>{league.deadlines?.[league.activeWeek]&&<p className="mt-3 text-amber-300">Custom deadline: {new Date(league.deadlines[league.activeWeek]).toLocaleString()}</p>}</section>
 {owner&&<>
 <form className={`${panel} space-y-5`} onSubmit={e=>{e.preventDefault();void act('settings',form);}}><h2 className="text-xl font-bold">Commissioner settings</h2><LeagueConfigFields value={form} onChange={setForm} existing/><button disabled={busy} className={primary}>Save league settings</button></form>
 <form className={`${panel} space-y-4`} onSubmit={e=>{e.preventDefault();void act('deadline',{week:league.activeWeek,deadline:new Date(deadline).toISOString()});}}><h2 className="text-xl font-bold">Set this week’s earlier deadline</h2><p className="text-sm text-slate-400">Set it before anyone submits picks and no later than the first kickoff. Times below use your device’s time zone.</p><label className="block">Week {league.activeWeek} deadline<input className={field} type="datetime-local" required value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button disabled={busy} className={primary}>Set deadline</button></form>
 {league.config.format==='survivor'&&league.activeWeek>1&&<form className={`${panel} space-y-4 border-amber-800`} onSubmit={e=>{e.preventDefault();const confirmation=window.prompt(`Type ${league.name} to confirm the Week ${league.startWeek} historical backfill.`);if(confirmation)void act('backfill',{confirmation});}}><h2 className="text-xl font-bold text-amber-200">Backfill Week {Math.max(1,league.startWeek-1)}</h2><p className="text-sm text-slate-400">Use this for a launch league that began after games started. It records entries 1–8 as Jaguars, Jaguars, Chargers, Chargers, Lions, Raiders, Eagles, and Steelers, then leaves the league ready for the current week.</p><button disabled={busy} className={primary}>Record historical Week {Math.max(1,league.startWeek-1)} picks</button></form>}
 <form className={`${panel} space-y-4`} onSubmit={e=>{e.preventDefault();void act('transfer',{userId:nextOwner});}}><h2 className="text-xl font-bold">Transfer commissioner role</h2><p className="text-sm text-slate-400">The selected member will control league settings and resets. Your entries stay in the league.</p><select aria-label="New commissioner" className={field} value={nextOwner} required onChange={e=>setNextOwner(e.target.value)}><option value="">Choose a member</option>{league.members.filter((m:any)=>m.userId!==league.me).map((m:any)=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select><button disabled={busy||!nextOwner} className={primary}>Transfer ownership</button></form>
 <details className="rounded-2xl border border-amber-900 p-6"><summary className="text-amber-300 font-bold cursor-pointer">Reset league or start a new season</summary><p className="text-sm text-slate-400 mt-4">These actions archive the current picks, then clear the active competition’s picks. Accounts, members, and entry names stay intact. No other league is affected. A regular week change does not require a reset.</p><label className="block mt-4">Starting week<select className={field} value={startWeek} onChange={e=>setStartWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=>i+1).map(w=><option key={w} value={w}>Week {w}</option>)}</select></label><label className="block mt-4">Type “{league.name}” to confirm<input className={field} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className={`${primary} mt-4`} disabled={busy||confirmation!==league.name} onClick={()=>act('reset',{confirmation,startWeek})}>Archive picks & reset this league</button><label className="block mt-6">New season<input type="number" className={field} value={season} min={league.season+1} max={2030} onChange={e=>setSeason(Number(e.target.value))}/></label><button className={`${primary} mt-4`} disabled={busy||confirmation!==league.name} onClick={()=>act('rollover',{confirmation,startWeek,season})}>Archive season & start new season</button></details>
 </>}
 <section className={panel}><h2 className="font-bold text-xl mb-3">Recent league activity</h2><ul className="space-y-2 text-sm text-slate-400">{league.audit.slice(-15).reverse().map((a:any,i:number)=><li key={i}>{a.action} · {league.members.find((m:any)=>m.userId===a.actor)?.name||'Former member'} · {new Date(a.at).toLocaleString()}</li>)}{!league.audit.length&&<li>No changes recorded yet.</li>}</ul></section>
 </div>;
}
