'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useAccount} from './AccountProvider';
import LeagueConfigFields,{defaults,field,panel,primary} from './LeagueConfigFields';
import {hq} from '@/lib/hq/client';
export default function LeagueDirectory({mode='list',title='Your leagues'}:{mode?:string;title?:string}) {
 const {session,loading,boot,error:accountError,refresh}=useAccount();const router=useRouter();const [form,setForm]=useState({...defaults});const [startWeek,setStartWeek]=useState(1);const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(boot?.meta)setStartWeek(boot.meta.week);},[boot?.meta?.week]);
 useEffect(()=>{const c=new URLSearchParams(window.location.search).get('code');if(c)setCode(c.toUpperCase());},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const data=await hq(mode==='create'?{action:'create',...form,season:boot.meta.season,startWeek}:{action:'join',code});await refresh();router.push(`/leagues/${data.league.id}`);}catch(e){setError(e instanceof Error?e.message:'Could not save this league.');}finally{setBusy(false);}}
 if(loading)return <p className="p-8 text-slate-400">Loading your account…</p>;
 if(!session)return <div className={`${panel} max-w-xl mx-auto space-y-4`}><h1 className="text-3xl font-black">Your NFL league starts here.</h1><p className="text-slate-400">Sign in to join friends, save picks, and track your entries across devices.</p><Link href={`/login?next=${encodeURIComponent(mode==='join'?`/leagues/join${code?'?code='+code:''}`:mode==='create'?'/leagues/create':'/leagues')}`} className={`${primary} inline-block`}>Sign in / Create account</Link></div>;
 return <div className="max-w-5xl mx-auto space-y-6"><header className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-xs text-emerald-400 font-bold tracking-widest uppercase">{boot?.meta?`NFL ${boot.meta.season} · Week ${boot.meta.week}`:'Survivor HQ'}</p><h1 className="text-3xl font-black mt-2">{mode==='create'?'Create a league':mode==='join'?'Join your friends':title}</h1></div><div className="flex flex-wrap gap-3"><Link className="text-emerald-400 underline" href="/leagues/create">Create league</Link><Link className="text-emerald-400 underline" href="/leagues/join">Join with code</Link>{mode!=='list'&&<Link href="/leagues" className="text-slate-400 underline">My leagues</Link>}</div></header>
 {boot?.warning&&<p className="p-4 rounded-xl bg-amber-950 text-amber-200">{boot.warning}</p>}
 {(error||accountError)&&<div role="alert" className="rounded-xl p-4 bg-rose-950 text-rose-200">{error||accountError}<button className="underline ml-3" onClick={refresh}>Retry loading</button></div>}
 {mode!=='list'?<form className={`${panel} max-w-2xl space-y-5`} onSubmit={submit}>{mode==='create'?<><LeagueConfigFields value={form} onChange={setForm}/><label className="block">Starting week<select className={field} value={startWeek} onChange={e=>setStartWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=>i+1).filter(w=>w>=(boot?.meta?.week||1)).map(w=><option value={w} key={w}>Week {w}</option>)}</select></label><p className="text-sm text-slate-400">Choose an unstarted week. You’ll receive one entry initially and can add more before the first kickoff.</p></>:<label className="block">Six-character invite code<input className={`${field} uppercase tracking-widest font-mono`} minLength={6} maxLength={6} required value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/></label>}<button disabled={busy||!boot?.meta} className={primary}>{busy?'Saving…':mode==='create'?'Create league':'Join league'}</button></form>:!boot?<p className="text-slate-400">Loading your saved leagues…</p>:boot.leagues.length===0?<section className={panel}><h2 className="text-xl font-bold">No leagues yet</h2><p className="text-slate-400 mt-2">Create a league or enter a friend’s invite code. Only leagues you actually belong to appear here.</p></section>:<div className="grid sm:grid-cols-2 gap-4">{boot.leagues.map((l:any)=><Link key={l.id} href={`/leagues/${l.id}`} className={`${panel} hover:border-emerald-600 transition-colors`}><p className="text-xs uppercase tracking-widest text-emerald-400">{l.format==='pickem'?'Straight Pick’em':l.format}</p><h2 className="text-xl font-bold mt-3">{l.name}</h2><p className="text-sm text-slate-400 mt-2">{l.season} · {l.memberCount} members · {l.entryCount} of your entries</p><p className="text-sm text-slate-300 mt-4">{l.owner?'Commissioner · ':''}Open league →</p></Link>)}</div>}
 </div>;
}
