'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountProvider';
import {hq} from '@/lib/hq/client';
import {panel,field} from './LeagueConfigFields';
export default function NflSchedule(){
 const {session,loading,boot}=useAccount();const [week,setWeek]=useState<number|null>(null);const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const generation=useRef(0);
 const activeLeague=(boot?.leagues||[]).find((league:any)=>!league.archived);const activeWeek=activeLeague?.activeWeek||boot?.meta?.week;
 useEffect(()=>{if(activeWeek&&week===null)setWeek(activeWeek);},[activeWeek,week]);
 async function load(){if(!boot?.meta||week===null)return;const seq=++generation.current;setBusy(true);setError('');try{const result=await hq({action:'schedule',season:boot.meta.season,week});if(seq===generation.current)setData(result);}catch(e){if(seq===generation.current)setError(e instanceof Error?e.message:'Schedule unavailable.');}finally{if(seq===generation.current)setBusy(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},60000);return()=>{clearInterval(timer);generation.current++;};},[week,boot?.meta?.season]);
 if(loading)return <p>Loading your account…</p>;
 if(!session)return <div className={panel}><h1 className="text-2xl font-black">NFL schedule</h1><Link className="inline-block text-emerald-400 underline mt-4" href="/login?next=/schedule">Sign in to see the schedule and your leagues</Link></div>;
 return <div className="space-y-6"><header className="flex flex-wrap justify-between gap-4 items-center"><div><p className="text-emerald-400 text-xs uppercase tracking-widest">{activeLeague?`${activeLeague.name} · `:''}ESPN · Regular season {boot?.meta?.season}</p><h1 className="text-3xl font-black mt-2">NFL schedule & scores</h1></div><label>Week<select className={field} value={week||1} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=>i+1).map(w=><option key={w} value={w}>{w}{w===activeWeek?' · active':''}</option>)}</select></label><button className="sports-action" disabled={busy} onClick={load}>{busy?'Refreshing…':'Refresh scores'}</button></header>{activeLeague&&<p className="text-xs text-slate-400">Following <strong className="text-slate-200">{activeLeague.name}</strong> · Week {activeWeek} is active. Choose another week anytime to browse ahead or review results.</p>}{error&&<p role="alert" className="p-4 bg-rose-950 text-rose-200 rounded-xl">{error}</p>}{data?.warning&&<p className="p-4 bg-amber-950 text-amber-200 rounded-xl">{data.warning}</p>}<p className="text-xs text-slate-500">Tap a team to open its Team Pulse and full schedule. Kickoff times use your device’s time zone. Last saved ESPN update: {data?.updated_at?new Date(data.updated_at).toLocaleString():'not yet'}.</p><div className="grid md:grid-cols-2 gap-4">{data?.games?.map((g:any)=><article className={panel} key={g.id}><div className="text-sm text-slate-400 flex justify-between gap-3 mb-4"><time>{new Date(g.kickoff).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time><span className={g.status==='live'?'text-emerald-400 font-bold':''}>{g.status==='scheduled'?'Scheduled':g.detail}</span></div>{[g.away,g.home].map((team:any)=><Link href={`/teams/${team.code}`} key={team.id} className="group flex items-center gap-3 rounded-xl py-3 transition-colors hover:bg-slate-800/70 hover:px-2"><img className="w-10 h-10 object-contain" alt="" src={team.logo}/><div className="flex-1"><p className="font-bold group-hover:text-emerald-300">{team.name}</p><p className="text-xs text-slate-500">{team.record} · {team.id===g.home.id?'Home':'Away'} · Team Pulse →</p></div>{['live','final'].includes(g.status)&&<span className="text-xl font-black">{team.id===g.home.id?g.homeScore:g.awayScore}</span>}</Link>)}</article>)}</div>{!busy&&data&&!data.games.length&&<p className={panel}>ESPN has not supplied games for this week yet.</p>}<Link href="/picks" className="inline-block text-emerald-400 underline">Choose a league to make picks →</Link></div>;
}
