'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {supabase} from '@/lib/supabaseClient';
import {hq} from '@/lib/hq/client';
import {useAccount} from '@/components/AccountProvider';
const field='mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white';
const button='rounded-xl bg-emerald-400 px-5 py-3 text-slate-950 font-bold disabled:opacity-40';
const emailsEnabled=process.env.NEXT_PUBLIC_AUTH_EMAILS_ENABLED==='true';
const avatars=['🏈','🛡️','🏆','⚡','🎯','🦅','🐅','⭐'];
export default function AccountPage(){
 const {session,loading,boot,refresh,error:accountError}=useAccount();const router=useRouter();
 const [mode,setMode]=useState('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [avatar,setAvatar]=useState('🏈');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [deletion,setDeletion]=useState('');const [recovery,setRecovery]=useState(false);
 useEffect(()=>{setRecovery(new URLSearchParams(window.location.search).get('recovery')==='1');const {data}=supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')setRecovery(true);});return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(boot?.profile){setName(boot.profile.display_name);setAvatar(boot.profile.avatar);}},[boot?.profile]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Unable to complete this action.');}finally{setBusy(false);}}
 function destination(){const raw=new URLSearchParams(window.location.search).get('next');return raw?.startsWith('/')&&!raw.startsWith('//')?raw:'/leagues';}
 async function authenticate(e:React.FormEvent){e.preventDefault();await run(async()=>{
  if(mode==='forgot'){if(!emailsEnabled)throw new Error('Email password recovery is not configured for this friends launch.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/login?recovery=1`});if(error)throw error;setMessage('If that email has an account, a password reset link is on its way.');return;}
  if(mode==='signup'){
   const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name.trim()},emailRedirectTo:`${window.location.origin}/login?next=${encodeURIComponent(destination())}`}});if(error)throw error;
   if(!data.session){setMessage('Check your email to confirm your account, then sign in.');setMode('login');setPassword('');return;}
  }else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
  router.push(destination());
 });}
 if(loading)return <p className="p-8 text-slate-400">Restoring your session…</p>;
 return <div className="max-w-xl mx-auto space-y-5"><header><p className="text-emerald-400 text-xs uppercase tracking-widest font-bold">Your account</p><h1 className="text-3xl font-black mt-2">{session?'Profile & account':mode==='signup'?'Join Survivor HQ':mode==='forgot'?'Reset your password':'Welcome back'}</h1></header>
 {(error||accountError)&&<p role="alert" className="p-4 rounded-xl bg-rose-950 text-rose-200">{error||accountError}</p>}{message&&<p role="status" className="p-4 rounded-xl bg-emerald-950 text-emerald-200">{message}</p>}
 {!session?<form onSubmit={authenticate} className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">{mode==='signup'&&<label className="block">Display name<input required minLength={2} maxLength={40} value={name} onChange={e=>setName(e.target.value)} className={field} autoComplete="nickname"/></label>}<label className="block">Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className={field} autoComplete="email"/></label>{mode!=='forgot'&&<label className="block">Password<input type="password" required minLength={mode==='signup'?8:1} value={password} onChange={e=>setPassword(e.target.value)} className={field} autoComplete={mode==='signup'?'new-password':'current-password'}/></label>}<button disabled={busy} className={`${button} w-full`}>{busy?'Please wait…':mode==='signup'?'Create account':mode==='forgot'?'Send reset link':'Sign in'}</button><div className="flex flex-wrap gap-4 text-sm text-emerald-400"><button type="button" onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('');}}>{mode==='signup'?'Already have an account?':'Create an account'}</button>{emailsEnabled&&<button type="button" onClick={()=>{setMode(mode==='forgot'?'login':'forgot');setError('');}}>{mode==='forgot'?'Back to sign in':'Forgot password?'}</button>}</div></form>:<>
 <form onSubmit={e=>{e.preventDefault();void run(async()=>{await hq({action:'profile',displayName:name,avatar});await refresh();setMessage('Profile saved.');});}} className="rounded-2xl border border-slate-800 bg-slate-900 p-6 space-y-4"><p className="text-slate-400 text-sm break-all">{session.user.email}</p><label className="block">Display name<input className={field} required minLength={2} maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><fieldset><legend className="mb-3">Avatar</legend><div className="flex flex-wrap gap-2">{avatars.map(a=><button type="button" aria-label={`Avatar ${a}`} aria-pressed={avatar===a} key={a} onClick={()=>setAvatar(a)} className={`text-2xl p-3 rounded-xl border ${avatar===a?'border-emerald-400 bg-emerald-950':'border-slate-700'}`}>{a}</button>)}</div></fieldset><button className={button} disabled={busy||!boot?.profile}>Save profile</button><Link href="/leagues" className="ml-4 text-emerald-400 text-sm underline">My leagues</Link></form>
 <details open={recovery} className="rounded-2xl border border-slate-800 p-6"><summary className="font-bold cursor-pointer">{recovery?'Choose your new password':'Change password'}</summary><form className="space-y-4 mt-4" onSubmit={e=>{e.preventDefault();void run(async()=>{if(newPassword!==confirmPassword)throw new Error('The passwords do not match.');const {error}=await supabase.auth.updateUser({password:newPassword});if(error)throw error;setNewPassword('');setConfirmPassword('');setRecovery(false);setMessage('Password updated.');});}}><label className="block">New password<input className={field} type="password" minLength={8} required autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label className="block">Confirm password<input className={field} type="password" minLength={8} required autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className={button} disabled={busy}>Update password</button></form></details>
 <button className="text-slate-300 underline" disabled={busy} onClick={()=>run(async()=>{const {error}=await supabase.auth.signOut();if(error)throw error;localStorage.removeItem('survivor_user_session');setMessage('Signed out.');})}>Sign out</button>
 <details className="rounded-2xl border border-rose-900 p-6"><summary className="font-bold text-rose-300 cursor-pointer">Delete my account</summary><p className="mt-4 text-sm text-slate-400">This permanently removes your account and profile. Historical league picks remain under “Deleted player.” Transfer any shared leagues you commission first.</p><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await hq({action:'deleteAccount',confirmation:deletion});await supabase.auth.signOut();setMessage('Your account was deleted.');setDeletion('');});}}><label className="block text-sm">Type DELETE MY ACCOUNT<input className={field} value={deletion} onChange={e=>setDeletion(e.target.value)} required/></label><button className="rounded-xl bg-rose-800 p-3 font-bold disabled:opacity-30" disabled={busy||deletion!=='DELETE MY ACCOUNT'}>Permanently delete account</button></form></details>
 </>}
 {!emailsEnabled&&<p className="text-sm text-amber-200 rounded-xl bg-amber-950/30 p-4">For this friends launch, email addresses are not verified and email password recovery is unavailable. Use an address you own and keep your password saved. You can change your password while signed in.</p>}
 <p className="text-sm text-slate-500">Profiles and league data are stored in Supabase. NFL schedules and scores come from ESPN. Buy-in amounts are tracking fields; this app does not collect payments.</p></div>;
}
